---
# tasks file for k8s-yum-upgrade
- name: change mirror
  ansible.builtin.shell: : sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*

- name: Change repos
  ansible.builtin.shell: : sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
